[profile.default]
src = "src"
out = "out"
libs = ["lib"]


[profile.ci]
src  = "src"
test = "test"
out  = "out"
libs = ["lib"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
